plugins {
    id 'net.consensys.besu-plugin-distribution' version '0.2.0'
}

allprojects {
  repositories {
    mavenLocal()
    mavenCentral()

    def silaJavaAuthoritiesRepo = ivy {
      url = uri('https://github.com/sila-chain/sila-besu/releases/download')
      patternLayout {
        artifact '/sila-java-authorities-v1/[artifact]-[revision].[ext]'
      }
      metadataSources { artifact() }
    }
    exclusiveContent {
      forRepositories(silaJavaAuthoritiesRepo)
      filter { includeGroup('sila.java') }
    }
  }
}

group = 'org.hyperledger.besu.tests'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    archiveFileName = 'outdatedTestPlugins.jar'
    manifest {
        attributes(
                'Specification-Title': archiveBaseName,
                'Specification-Version': project.version,
                'Implementation-Title': archiveBaseName,
                'Implementation-Version': project.version
        )
    }
}