apply plugin: 'java-library'

compileJava {
  options.errorprone {
    check('NullAway', net.ltgt.gradle.errorprone.CheckSeverity.ERROR)
    option('NullAway:AnnotatedPackages', 'org.hyperledger.besu.consensus.ibftlegacy')
  }
}

tasks.named('compileTestJava', JavaCompile).configure {
  options.errorprone {
    check('NullAway', net.ltgt.gradle.errorprone.CheckSeverity.OFF)
  }
}

tasks.matching { it.name == 'compileIntegrationTestJava' }.configureEach {
  options.errorprone {
    check('NullAway', net.ltgt.gradle.errorprone.CheckSeverity.OFF)
  }
}

jar {
  archiveBaseName = calculateArtifactId(project)
  manifest {
    attributes(
      'Specification-Title': archiveBaseName,
      'Specification-Version': project.version,
      'Implementation-Title': archiveBaseName,
      'Implementation-Version': calculateVersion(),
      'Commit-Hash': getGitCommitDetails(40).hash
      )
  }
}

dependencies {
  implementation project(':config')
  implementation project(':consensus:common')
  implementation project(':consensus:ibft')
  implementation project(':crypto:algorithms')
  implementation project(':datatypes')
  implementation project(':sila:api')
  implementation project(':sila:blockcreation')
  implementation project(':sila:core')
  implementation project(':sila:sil')
  implementation project(':sila:p2p')
  implementation project(':sila:rlp')
  implementation project(':savm')
  implementation project(':metrics:core')
  implementation project(':services:kvstore')

  implementation 'com.google.guava:guava'
  implementation 'io.vertx:vertx-core'
  implementation 'com.fasterxml.jackson.core:jackson-databind'
  implementation 'io.consensys.tuweni:tuweni-bytes'
  implementation 'io.consensys.tuweni:tuweni-units'

  errorprone 'com.uber.nullaway:nullaway'

  compileOnlyApi 'org.jspecify:jspecify'

  testImplementation project(path: ':consensus:common', configuration: 'testSupportArtifacts')
  testImplementation project(path: ':consensus:ibft', configuration: 'testSupportArtifacts')
  testImplementation project(path: ':sila:core', configuration: 'testSupportArtifacts')
  testImplementation project(path: ':sila:sil', configuration: 'testSupportArtifacts')
  testImplementation project(':metrics:core')
  testImplementation project(':testutil')

  integrationTestImplementation 'org.assertj:assertj-core'
  integrationTestImplementation 'org.junit.jupiter:junit-jupiter-api'
  integrationTestImplementation 'org.mockito:mockito-core'
  integrationTestImplementation 'org.mockito:mockito-junit-jupiter'

  testImplementation 'org.assertj:assertj-core'
  testImplementation 'org.junit.jupiter:junit-jupiter'
  testImplementation 'org.awaitility:awaitility'
  testImplementation 'org.mockito:mockito-core'
  testImplementation 'org.mockito:mockito-junit-jupiter'
}
